from collections import OrderedDict

publications = OrderedDict()
publications['2022'] = [
	"""Wu, W., Z.-L. Yang, L. Zhao, <b><u>P. Lin</b></u>: The impact of multi-sensor land data assimilation on river discharge estimation. <i>Remote Sensing of Environment</i>. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0034425722002528#:~:text=It%20is%20found%20that%20assimilating,skillful%20during%20the%20boreal%20summer">link</a>""",
	"""Krabbenhoft, C. G. Allen, <b><u>P. Lin</b></u>, and co-authors: Assessing placement bias of the global river gauge network. <i>Nature Sustainability</i>. </i><a href="https://www.nature.com/articles/s41893-022-00873-0">link</a>""",
	"""Liu, S., C. Kuhn, G. Amatulli, K. Aho, D. Butman, G.H. Allen, <b><u>P. Lin</b></u>, M. Pan, D. Yamazaki, C. Brinkerhoff, C. Gleason, P. Raymond: The importance of hydrology in routing terrestrial carbon to the atmosphere via global streams and rivers, <i>Proceedings of the National Academy of Sciences of the United States of America</i>. </i><a href="https://www.pnas.org/doi/10.1073/pnas.2106322119">link</a>""",
	"""Riggs, R., G. Allen, C. David, <b><u>P. Lin</b></u>, M. Pan, X. Yang, C. Gleason: RODEO: An algorithm and Google Earth Engine application for river discharge retrieval from Landsat, <i>Environmental Modelling & Software</i>. </i><a href="https://www.sciencedirect.com/science/article/abs/pii/S1364815221002966">link</a>"""
]

publications['2021'] = [
	"""<b><u>Lin, P.</b></u>, Pan, M., E.F. Wood, D. Yamazaki, G. Allen: A new vector-based global river network dataset accounting for variable drainage density. <i>Scientific Data</i>. <a href="https://www.nature.com/articles/s41597-021-00819-9">link</a>""",
	"""Feng, D., C. Gleason, <b><u>P. Lin</b></u>, X. Yang, M. Pan, Y. Ishitsuka: Recent changes to Arctic river discharge. <i>Nature communications. </i><a href="https://www.nature.com/articles/s41467-021-27228-1">link</a>""",
	"""Zeng, Z., D. Wang, L. Yang, J. Wu, A.D. Ziegler, M. Liu, P. Ciais, T. Searchinger, Z.L. Yang, D. Chen, A. Chen, L. Li, S. Piao, D. Taylor, X. Cai, M. Pan, L. Peng, <b><u>P. Lin</b></u>, D. Gower, Y. Feng, C. Zheng, K. Guan, X. Lian, T. Wang, L. Wang, S. Jeong, Z. Wei, J. Sheffield, K. Caylor, E. Wood: Deforestation-induced warming over tropical mountain regions regulated by elevation. <i>Nature Geoscience. </i><a href="https://www.nature.com/articles/s41561-020-00666-0">link</a>""",
	"""Chao, L., K. Zhang, Z.-L. Yang, J. Wang, <b><u>P. Lin</b></u>, J. Liang, Z. Li, Z. Gu: Improving flood simulation capability of the WRF-Hydro-RAPID model using a multi-source precipitation merging method. <i>Journal of Hydrology. </i><a href="https://www.sciencedirect.com/science/article/abs/pii/S0022169420312750">link</a>""",
	"""Peng L., Z. Wei, Z. Zeng, <b><u>P. Lin</b></u>, E.F. Wood, J. Sheffield: Reducing solar radiation forcing uncertainty and its impact on surface energy and water fluxes. <i>Journal of Hydrometeorology. </i><a href="https://journals.ametsoc.org/view/journals/hydr/22/4/JHM-D-20-0052.1.xml">link</a>""",
	"""Yang, Y, M. Pan, <b><u>P. Lin</b></u>, H. Beck, Z. Zeng, D. Yamazaki, C. David, H. Lu, K. Yang, Y. Hong, E. Wood: Global Reach-level 3-hourly River Flood Reanalysis (1980-2019). <i>Bulletin of the American Meteorological Society. </i><a href="https://journals.ametsoc.org/view/journals/bams/102/11/BAMS-D-20-0057.1.xml">link</a>""",
	"""Frasson, R., M. Durand, K. Larnier, C. Gleason, K. Andreadis, M. Hagemann, R. Dudley, D. Bjerklie, H. Oubanas, P.A. Garambois, P.O. Malaterre, <b><u>P. Lin</b></u>, T. Pavelsky, J. Monnier, C. Brinkerhoff, C. David: Exploring the factors controlling the error characteristics of the Surface Water and Ocean Topography mission discharge estimates. <i>Water Resources Research. </i><a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020WR028519">link</a>""",
	"""Mizukami, N., M. Clark, S. Gharari, E. Kluzek, M. Pan, <b><u>P. Lin</b></u>, H.E. Beck, D. Yamazaki: A vector-based river routing model for Earth System Models: Parallelization and global applications, <i>Journal of Advances in Modeling Earth Systems. </i><a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020MS002434">link</a>""",
	"""Fei, W., H. Zheng, Z. Xu, W. Wu, <b><u>P. Lin</b></u>, Y. Tian, M. Guo, D. She, L. Li, K. Li, Z.L. Yang: Ensemble skill gains obtained from the multi-physics versus multi-model approaches for continental-scale hydrologic simulations. <i>Water Resources Research. </i><a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020WR028846">link</a>""",
	"""Jiang, X., S. Liang, X. He, A. Ziegler, <b><u>P. Lin</b></u>, M. Pan, D. Wang, J. Zou, D. Hao, G. Mao, Y. Zeng, J. Yin, L. Feng, C. Miao, E. Wood, Z. Zeng: Rapid and large-scale mapping of flood inundation via integrating spaceborne synthetic aperture radar imagery with unsupervised deep learning. <i>ISPRS Journal of Photogrammetry and Remote Sensing. </i><a href="https://www.sciencedirect.com/science/article/abs/pii/S0924271621001520">link</a>""",
	"""Jiang, Z., L. Feng, S. Li, J. Wang, X. Cai, <b><u>P. Lin</b></u>, X. Wang, H. Zhao: The dynamics of hongjian nur, the largest desert freshwater lake in china, during 1990–2017. <i>Remote Sensing. </i><a href="https://www.mdpi.com/2072-4292/13/14/2690">link</a>""",
	"""Gao, S., Z. Li, M. Chen, <b><u>P. Lin</b></u>, Z. Hong, D. Allen, T. Neeson, Y. Hong: Spatiotemporal variability of global river extent and the natural driving factors revealed by decades of Landsat observations, GRACE gravimetry observations, and land surface model simulations. <i>Remote Sensing of Environment. </i><a href="https://www.sciencedirect.com/science/article/abs/pii/S0034425721004454">link</a>""",
]

publications['2020'] = [
	"""<b><u>Lin, P.</b></u>, Pan, M., Allen, G., Frasson, R., Zeng, Z., Yamazaki, D., Wood, E.: Global estimates of reach-level bankfull river width leveraging big-data geospatial analysis, <i>Geophysical Research Letters</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019GL086405">link</a>""",
	"""<b><u>Lin, P.</b></u>, ZL Yang, J. Wei, RE Dickinson, Y. Zhang, L. Zhao: Assimilating multi-satellite snow data in ungauged Eurasia improves the simulation accuracy of Asian monsoon seasonal anomalies. <i>Environmental Research Letters</i>. <a href="https://iopscience.iop.org/article/10.1088/1748-9326/ab80ef">link</a> <a href="https://www.sciencedaily.com/releases/2020/07/200716120705.htm"><bMedia Report<b></a>""",
	"""Brinkerhoff, C., C. Gleason, D. Feng, <b><u>P. Lin</b></u>: Constraining Remote River Discharge Estimation Using Reach-Scale Geomorphology. <i>Water Resources Research</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020WR027949">link</a>""",
	"""Zhang, J.*, <b><u>P. Lin</b></u>, S. Gao, N.Z. Fang: Understanding the Re-infiltration Process to Simulating Streamflow in North Central Texas using the WRF-Hydro Modeling System. <i>Journal of Hydrology</i>.  (* graduate advisee) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0022169420303620">link</a>""",
	"""Beck, H, M Pan, <b><u>P. Lin</b></u>, J Seibert, A van Dijk, EF Wood: Global fully-distributed parameter regionalization based on observed streamflow from 4229 headwater catchments. <i>JGR-Atmosphere</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JD031485">link</a>""",
	"""Zheng, H., Z.-L. Yang, <b><u>P. Lin</b></u>, et al.: Falsification-oriented signature-based evaluation for guiding development of land surface models and the enhancement of observations. <i>Journal of Advances in Modeling Earth Systems</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020MS002132">link</a>""",
	"""Zeng, et al. including <b><u>P. Lin</b></u>: Deforestation-induced warming over tropical mountain regions regulated by elevation. <i>Nature Geoscience</i>. <a href="https://www.nature.com/articles/s41561-020-00666-0">link</a>""",
	"""Ishitsuka, Y., Gleason, C., Hagemann, M., Beighley, E., Allen, G., Feng, D., <b><u>P. Lin</b></u>, M. Pan, Andreadis, K., Pavelsky, T.: Combining Optical Remote Sensing, McFLI Discharge Estimation, Global Hydrologic Modeling, and Data Assimilation to Improve Daily Discharge Estimates Across an Entire Large Watershed. <i>Water Resources Research</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020WR027794">link</a>""",
	"""Sikder Md. S., M. Bonnema, C.M. Emery, C.H. David, <b><u>P. Lin</b></u>, M. Pan, S. Biancamaria, M.M. Gierach: A synthetic dataset inspired by satellite altimetry and impacts of sampling on global spaceborne discharge characterization. <i>Water Resources Research</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020WR029035">link</a>""",
	"""Wu, J., V. Lakshmi, D. Wang, <b><u>P. Lin</b></u>, M. Pan, X. Cai, E.F. Wood, Z. Zeng: The reliability of global remote sensing evapotranspiration products over Amazon. <i>Remote Sensing</i>. <a href="https://www.mdpi.com/2072-4292/12/14/2211">link</a>""",
	"""Li, L., She, S., Zheng, H., <b><u>P. Lin</b></u>, Yang, ZL.: Elucidating diverse drought characteristics from two meteorological drought indices (SPI and SPEI) in China. <i>Journal of Hydrometeorology</i>. <a href="https://journals.ametsoc.org/view/journals/hydr/21/7/jhmD190290.xml">link</a>""",
	"""Yu, S., Do, H. X., van Dijk, A. I. J. M., Bond, N. R., <b><u>Lin, P.</b></u>, and Kennard, M. J.: Evaluating a landscape-scale daily water balance model to support spatially continuous representation of flow intermittency throughout stream networks, <i>Hydrol. Earth Syst. Sci</i>. <a href="https://hess.copernicus.org/articles/24/5279/2020/">link</a>""",
	"""Liu et. al including <b><u>P. Lin</b></u>: High spatiotemporal resolution mapping of global urban change from 1985 to 2015. <i>Nature Sustainability</i>. <a href="https://www.nature.com/articles/s41893-020-0521-x">link</a>""",
	"""Liang, J., Z.-L. Yang, X. Cai, <b><u>P. Lin</b></u>, H. Zheng: Modeling the impacts of nitrogen dynamics on regional terrestrial carbon and water cycles over China with Noah-MP-CN. <i>Advances in Atmospheric Sciences</i>. <a href="https://link.springer.com/article/10.1007/s00376-020-9231-6">link</a>""",
	"""Roy, T., He, X., <b><u>P. Lin</b></u>, Beck, H., Castro, C., Wood, E.: Global evaluation of seasonal precipitation and temperature forecasts from NMME. <i>J. Hydrometeorology</i>. <a href="https://journals.ametsoc.org/view/journals/hydr/21/11/JHM-D-19-0095.1.xml">link</a>""",
	"""Liu, Y., Yang, Z.-L., <b><u>Lin, P.</b></u>, Zheng, Z., Xie, S.: Comparison and evaluation of multiple land surface products for the water budget in the Yellow River Basin. <i>Journal of Hydrology</i>. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0022169419312697">link</a>"""
]

publications['2019'] = [
	"""<b><u>Lin, P.</b></u>, M. Pan, H.E. Beck, Y. Yang, D. Yamazaki, R. Frasson, C.H. David, M. Durand, T. Pavelsky, G. Allen, C. Gleason, E.F. Wood: Global reconstruction of naturalized river flows at 2.94 million reaches. <i>Water Resources Research</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025287">link</a> <a href="https://eos.org/editor-highlights/reconstructing-natural-streamflow-at-unprecedented-resolution"><b>Eos Editor's Highlight</b</a>""",
	"""Yang, Y, <b><u>P. Lin</b></u>, M. Pan et al.: Enhancing gap-filling in SWOT discharge interpolation through spatio-temporal correlations. <i>Remote Sensing of Environment</i>. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0034425719304699">link</a>""",
	"""Liang, J., Z.-L. Yang, <b><u>P. Lin</b></u>: Systematic hydrological evaluation of the Noah-MP land surface model over China. <i>Advances in Atmospheric Research</i>. <a href="https://link.springer.com/article/10.1007/s00376-019-9016-y">link</a>""",
	"""Zheng, H., Z.-L. Yang, <b><u>P. Lin</b></u>, et al.: On the sensitivity of precipitation partitioning into evapotranspiration and runoff in land surface parameterizations. <i>Water Resources Research</i>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2017WR022236">link</a>"""
]
publications['prior to 2018 (graduate)'] = [
	"""<b><u>Lin, P.</b></u>, L.J. Hopper Jr., Z.-L. Yang, M. Lenz, J.W. Zeitler (2018): Insights into hydrometeorological factors constraining flood prediction skill during the May and October 2015 Texas Hill Country flood events. <i>Journal of Hydrometeorology</i>. <a href="https://journals.ametsoc.org/view/journals/hydr/19/8/jhm-d-18-0038_1.xml">link</a>""",
	"""<b><u>Lin P.</b></u>, Z.-L. Yang, D.J. Gochis, Y. Wei, D.R. Maidment, M.A. S.-Valenzuela, C.H. David (2018): Implementation of a vector-based river network routing model in the community WRF-Hydro system for flood discharge simulation. <i>Environmental Modelling & Software</i>. <a href="https://www.sciencedirect.com/science/article/abs/pii/S1364815217313531">link</a>""",
	"""Jin, Q., J. Wei, Z.-L. Yang, <b><u>P. Lin</b></u> (2017): Irrigation-induced environmental changes around the Aral Sea: An integrated view from multiple satellite observations. <i>Remote Sensing</i>. <a href="https://www.mdpi.com/2072-4292/9/9/900">link</a>""",
	"""<b><u>Lin, P.</b></u>, M.Rajib, Z.-L. Yang, et al. (2017): Spatio-temporal evaluation of simulated evapotranspiration and streamflow over Texas using the WRF-Hydro-RAPID framework. <i>Journal of American Water Resource Association</i>. <a href="https://onlinelibrary.wiley.com/doi/10.1111/1752-1688.12585">link</a>""",
	"""(Edited) Maidment, D.R., A.D. Rajib, <b><u>P. Lin</b></u>, E.P. Clark (2016) (Eds): National Water Center Innovators Program Summer Institute Report. <i>Consortium of Universities for the Advancement of Hydrologic Science Inc</i>. <a href="https://www.cuahsi.org/uploads/library/doc/cuahsi_tr13_8.20.16.pdf">link</a>""",
	"""<b><u>Lin P.</b></u>, J. Wei, Z.-L. Yang, Y.-F. Zhang, K. Zhang (2016): Snow data assimilation-constrained land initialization improves seasonal temperature prediction. <i>Geophysical Research Letters</i>. <b>(picked up by 7 news outlets including Phys.org, ScienceDaily, etc.)</b>  <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016gl070966">link</a>""",
	"""<b><u>Lin P.</b></u>, Z.-L. Yang, X. Cai, C. H. David (2015): Development and evaluation of a physically-based lake level model for water resource management: A case study for Lake Buchanan, Texas. <i>Journal of Hydrology: Regional Studies</i>. <a href="https://www.sciencedirect.com/science/article/pii/S2214581815001056">link</a>"""
]
publications['2012 (undergraduate)'] = [
	"""<b><u>Lin P.</b></u>, Q. Qin, H. Dong, Q. Meng: Hyperspectral vegetation indices for crop chlorophyll estimation: Assessment, modeling and validation. <i>2012 IEEE International Geoscience and Remote Sensing Symposium</i>. <a href="https://ieeexplore.ieee.org/document/6352529">link</a>"""
]

working_papers = [

]
